/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as binaryVillRobotsNftSol from "./BinaryVillRobotsNFT.sol";
export type { binaryVillRobotsNftSol };
export type { Lock } from "./Lock";
