/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as binaryVillRobotsNftSol from "./BinaryVillRobotsNFT.sol";
export { Lock__factory } from "./Lock__factory";
